name: Release

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: |
        echo "Let's release this"
