name: Release

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
        #    paths:
        #      - 'src/**'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -L \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'\
          -H 'X-GitHub-Api-Version: 2022-11-28' \
          https://api.github.com/repos/safeith/demo/releases/latest
