name: Release

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
        #    paths:
        #      - 'src/**'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        LATEST_RELEASE=$(curl -s -L -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H 'X-GitHub-Api-Version: 2022-11-28' https://api.github.com/repos/safeith/demo/releases/latest | jq .tag_name | grep -Eo '[0-9]+' || 0)
        echo "NEW_RELEASE=$((LATEST_RELEASE + 1))" >> $GITHUB_ENV

    - run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/safeith/demo/releases \
          -d '{"tag_name":"v${{ env.NEW_RELEASE }}","target_commitish":"main","name":"v$i{{ NEW_RELEASE }}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}' 
