name: Revert

on:
  workflow_dispatch:
      
jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
    - name: Check # This checks if we have all required information to revert to a spesefic tag
      run: |
        echo "TAG NAME: ${{ github.ref_name }}"
        echo "The Content of the manifest file: "
        curl -s -L https://github.com/safeith/demo/releases/download/${{ github.ref_name }}/manifest.json
