name: Revert

on:
  workflow_dispatch:
      
jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo True
        echo "You are reverting to ${{ GITHUB_REF_NAME }}"
        echo "The manifest file coutent of this release is"
        curl https://github.com/safeith/demo/releases/download/${{ GITHUB_REF_NAME }}/manifest.json
