name: Revert

on:
  workflow_dispatch:
      
jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo True
        echo "You are reverting to ${{ github.ref_name }}"
        echo "The manifest file coutent of this release is"
        curl https://github.com/safeith/demo/releases/download/${{ github.ref_name }}/manifest.json
